import networkx as nx
import matplotlib.pyplot as plt

# School_map dictionary
school_map = {
    'Classroom1-3-B': {'Hallway3-B': {'Type': 'Hallway', 'Weight': 1}},
    'Classroom2-3-B': {'Hallway3-B': {'Type': 'Hallway', 'Weight': 1}},
    'Classroom3-3-B': {'Hallway3-B': {'Type': 'Hallway', 'Weight': 1}},
    'Classroom4-3-B': {'Hallway3-B': {'Type': 'Hallway', 'Weight': 1}},
    'Classroom5-3-B': {'Hallway3-B': {'Type': 'Hallway', 'Weight': 1}},
    'Classroom6-3-B': {'Hallway3-B': {'Type': 'Hallway', 'Weight': 1}},
    'Classroom7-3-B': {'Hallway3-B': {'Type': 'Hallway', 'Weight': 1}},
    'Classroom8-3-B': {'Hallway3-B': {'Type': 'Hallway', 'Weight': 1}},
    'Classroom1-3-C': {'Hallway3-C': {'Type': 'Hallway', 'Weight': 1}},
    'Classroom2-3-C': {'Hallway3-C': {'Type': 'Hallway', 'Weight': 1}},
    'Classroom3-3-C': {'Hallway3-C': {'Type': 'Hallway', 'Weight': 1}},
    'Classroom4-3-C': {'Hallway3-C': {'Type': 'Hallway', 'Weight': 1}},
    'Classroom5-3-C': {'Hallway3-C': {'Type': 'Hallway', 'Weight': 1}},
    'Classroom6-3-C': {'Hallway3-C': {'Type': 'Hallway', 'Weight': 1}},
    'Classroom7-3-C': {'Hallway3-C': {'Type': 'Hallway', 'Weight': 1}},
    'Classroom8-3-C': {'Hallway3-C': {'Type': 'Hallway', 'Weight': 1}},
    'Hallway0-B': {'Stairs0-B': {'Type': 'Stairs', 'Weight': 1},
                  'EmergencyExit0-B': {'Type': 'EmergencyExit', 'Weight': 1},
                  'MainHall': {'Type': 'Hallway', 'Weight': 1}},
    'Hallway1-B': {'Stairs1-B': {'Type': 'Stairs', 'Weight': 1},
                  'EmergencyExit1-B': {'Type': 'EmergencyExit', 'Weight': 1},
                  'Hallway1-C': {'Type': 'Hallway', 'Weight': 1}},
    'Hallway2-B': {'Stairs2-B': {'Type': 'Stairs', 'Weight': 1},
                  'EmergencyExit2-B': {'Type': 'EmergencyExit', 'Weight': 1},
                  'Hallway2-C': {'Type': 'Hallway', 'Weight': 1}},                  
    'Hallway3-B': {'Classroom1-3-B': {'Type': 'Classroom', 'Weight': 1},
                  'Classroom2-3-B': {'Type': 'Classroom', 'Weight': 1},
                  'Classroom3-3-B': {'Type': 'Classroom', 'Weight': 1},
                  'Classroom4-3-B': {'Type': 'Classroom', 'Weight': 1},
                  'Classroom5-3-B': {'Type': 'Classroom', 'Weight': 1},
                  'Classroom6-3-B': {'Type': 'Classroom', 'Weight': 1},
                  'Classroom7-3-B': {'Type': 'Classroom', 'Weight': 1},
                  'Classroom8-3-B': {'Type': 'Classroom', 'Weight': 1},
                  'Stairs3-B': {'Type': 'Stairs', 'Weight': 1},
                  'EmergencyExit3-B': {'Type': 'EmergencyExit', 'Weight': 1},
                  'Hallway3-C': {'Type': 'Hallway', 'Weight': 1}},
    'Stairs0-B': {'Hallway0-B': {'Type': 'Hallway', 'Weight': 1},
                  'Stairs1-B': {'Type': 'Stairs', 'Weight': 1}},
    'Stairs1-B': {'Hallway1-B': {'Type': 'Hallway', 'Weight': 1},
                  'Stairs2-B': {'Type': 'Stairs', 'Weight': 1},
                  'Stairs0-B': {'Type': 'Stairs', 'Weight': 1}},
    'Stairs2-B': {'Hallway2-B': {'Type': 'Hallway', 'Weight': 1},
                  'Stairs3-B': {'Type': 'Stairs', 'Weight': 1},
                  'Stairs1-B': {'Type': 'Stairs', 'Weight': 1}},
    'Stairs3-B': {'Hallway3-B': {'Type': 'Hallway', 'Weight': 1},
                  'Stairs2-B': {'Type': 'Stairs', 'Weight': 1}},
    'EmergencyExit0-B': {'Hallway0-B': {'Type': 'Hallway', 'Weight': 1},
                  'EmergencyExit1-B': {'Type': 'EmergencyExit', 'Weight': 1},
                  'Safe': {'Type': 'Safe', 'Weight': 1}},
    'EmergencyExit1-B': {'Hallway1-B': {'Type': 'Hallway', 'Weight': 1},
                  'EmergencyExit2-B': {'Type': 'EmergencyExit', 'Weight': 1},
                  'EmergencyExit0-B': {'Type': 'EmergencyExit', 'Weight': 1}},
    'EmergencyExit2-B': {'Hallway2-B': {'Type': 'Hallway', 'Weight': 1},
                  'EmergencyExit3-B': {'Type': 'EmergencyExit', 'Weight': 1},
                  'EmergencyExit1-B': {'Type': 'EmergencyExit', 'Weight': 1}},
    'EmergencyExit3-B': {'Hallway3-B': {'Type': 'Hallway', 'Weight': 1},
                  'EmergencyExit2-B': {'Type': 'EmergencyExit', 'Weight': 1}},
    'Hallway0-C': {'Stairs0-C': {'Type': 'Stairs', 'Weight': 1},
                  'Lift': {'Type': 'Lift', 'Weight': 1},
                  'MainHall': {'Type': 'Hallway', 'Weight': 1}},
    'Hallway1-C': {'Stairs1-C': {'Type': 'Stairs', 'Weight': 1},
                  'Lift': {'Type': 'Lift', 'Weight': 1},
                  'Hallway1-B': {'Type': 'Hallway', 'Weight': 1}},
    'Hallway2-C': {'Stairs2-C': {'Type': 'Stairs', 'Weight': 1},
                  'Lift': {'Type': 'Lift', 'Weight': 1},
                  'Hallway2-B': {'Type': 'Hallway', 'Weight': 1}},
    'Hallway3-C': {'Classroom1-3-C': {'Type': 'Classroom', 'Weight': 1},
                  'Classroom2-3-C': {'Type': 'Classroom', 'Weight': 1},
                  'Classroom3-3-C': {'Type': 'Classroom', 'Weight': 1},
                  'Classroom4-3-C': {'Type': 'Classroom', 'Weight': 1},
                  'Classroom5-3-C': {'Type': 'Classroom', 'Weight': 1},
                  'Classroom6-3-C': {'Type': 'Classroom', 'Weight': 1},
                  'Classroom7-3-C': {'Type': 'Classroom', 'Weight': 1},
                  'Classroom8-3-C': {'Type': 'Classroom', 'Weight': 1},
                  'Stairs3-C': {'Type': 'Stairs', 'Weight': 1},
                  'Lift': {'Type': 'Lift', 'Weight': 1},
                  'Hallway3-B': {'Type': 'Hallway', 'Weight': 1}},
    'Stairs0-C': {'Hallway0-C': {'Type': 'Hallway', 'Weight': 1},
                  'Stairs1-C': {'Type': 'Stairs', 'Weight': 1}},
    'Stairs1-C': {'Hallway1-C': {'Type': 'Hallway', 'Weight': 1},
                  'Stairs2-C': {'Type': 'Stairs', 'Weight': 1},
                  'Stairs0-C': {'Type': 'Stairs', 'Weight': 1}},
    'Stairs2-C': {'Hallway2-C': {'Type': 'Hallway', 'Weight': 1},
                  'Stairs3-C': {'Type': 'Stairs', 'Weight': 1},
                  'Stairs1-C': {'Type': 'Stairs', 'Weight': 1}},
    'Stairs3-C': {'Hallway3-C': {'Type': 'Hallway', 'Weight': 1},
                  'Stairs2-C': {'Type': 'Stairs', 'Weight': 1}},
    'Lift': {'Hallway0-C': {'Type': 'Lift', 'Weight': 1},
                  'Hallway1-C': {'Type': 'Lift', 'Weight': 1},
                  'Hallway2-C': {'Type': 'Lift', 'Weight': 1},
                  'Hallway3-C': {'Type': 'Lift', 'Weight': 1}},
    'MainHall': {'Hallway0-B': {'Type': 'Hallway', 'Weight': 1},
                  'Hallway0-C': {'Type': 'Hallway', 'Weight': 1},
                  'Kantine': {'Type': 'Hallway', 'Weight': 1}},
    'Kantine': {'MainHall': {'Type': 'Hallway', 'Weight': 1}},
    'Safe': {'EmergencyExit0-B': {'Type': 'EmergencyExit', 'Weight': 1}}
}

# Create a directed networkx graph from the dictionary
G = nx.DiGraph(school_map)

# Visualize the graph
pos = nx.fruchterman_reingold_layout(G)
nx.draw(G, pos, with_labels=True, font_weight='bold', node_size=700, node_color='skyblue', font_color='black', font_size=8, arrowsize=10)
edge_labels = {(u, v): f"{u}-{v}" for u, v in G.edges()}
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels)

# Show the plot
plt.show()
